"$schema" = "https://starship.rs/config-schema.json"

format = "$directory$git_branch$git_status$line_break$character"
right_format = ""
continuation_prompt = "[∙](bright-black) "
scan_timeout = 10
command_timeout = 300
add_newline = true
follow_symlinks = true

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = "[$path]($style)[$read_only]($read_only_style) "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "cyan bold"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "purple bold"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold red"

[character]
format = "$symbol "
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"
vimcmd_symbol = "[«](bold green)"
vimcmd_visual_symbol = "[«](bold yellow)"
vimcmd_replace_symbol = "[«](bold purple)"
vimcmd_replace_one_symbol = "[«](bold purple)"
